
[build-system]
requires = ["setuptools >= 61.0",
            "pybind11",
            "cmake"]
build-backend = "setuptools.build_meta"

[project]
name = "roshambo2"
version = "2.0"
description = "3D molecular shape overlap"
